// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface AddInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.AddInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 i = 1;</code>
   * @return The i.
   */
  long getI();

  /**
   * <code>int64 j = 2;</code>
   * @return The j.
   */
  long getJ();
}
