// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface AddInputResposeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.AddInputRespose)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 result = 1;</code>
   * @return The result.
   */
  long getResult();
}
