// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface FileMetaDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.FileMetaDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double filelength = 2;</code>
   * @return The filelength.
   */
  double getFilelength();

  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   * @return Whether the dateModified field is set.
   */
  boolean hasDateModified();
  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   * @return The dateModified.
   */
  com.google.protobuf.Timestamp getDateModified();
  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateModifiedOrBuilder();
}
