// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

/**
 * Protobuf type {@code com.example.files.FileMetaDataResponse}
 */
public final class FileMetaDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.files.FileMetaDataResponse)
    FileMetaDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileMetaDataResponse.newBuilder() to construct.
  private FileMetaDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileMetaDataResponse() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileMetaDataResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileMetaDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 17: {

            filelength_ = input.readDouble();
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateModified_ != null) {
              subBuilder = dateModified_.toBuilder();
            }
            dateModified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateModified_);
              dateModified_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.files.FileMetadata.internal_static_com_example_files_FileMetaDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.files.FileMetadata.internal_static_com_example_files_FileMetaDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.files.FileMetaDataResponse.class, com.example.files.FileMetaDataResponse.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILELENGTH_FIELD_NUMBER = 2;
  private double filelength_;
  /**
   * <code>double filelength = 2;</code>
   * @return The filelength.
   */
  @java.lang.Override
  public double getFilelength() {
    return filelength_;
  }

  public static final int DATEMODIFIED_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp dateModified_;
  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   * @return Whether the dateModified field is set.
   */
  @java.lang.Override
  public boolean hasDateModified() {
    return dateModified_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   * @return The dateModified.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDateModified() {
    return dateModified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateModified_;
  }
  /**
   * <code>.google.protobuf.Timestamp dateModified = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDateModifiedOrBuilder() {
    return getDateModified();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (filelength_ != 0D) {
      output.writeDouble(2, filelength_);
    }
    if (dateModified_ != null) {
      output.writeMessage(3, getDateModified());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (filelength_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, filelength_);
    }
    if (dateModified_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDateModified());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.files.FileMetaDataResponse)) {
      return super.equals(obj);
    }
    com.example.files.FileMetaDataResponse other = (com.example.files.FileMetaDataResponse) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (java.lang.Double.doubleToLongBits(getFilelength())
        != java.lang.Double.doubleToLongBits(
            other.getFilelength())) return false;
    if (hasDateModified() != other.hasDateModified()) return false;
    if (hasDateModified()) {
      if (!getDateModified()
          .equals(other.getDateModified())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FILELENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFilelength()));
    if (hasDateModified()) {
      hash = (37 * hash) + DATEMODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getDateModified().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.files.FileMetaDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.files.FileMetaDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.files.FileMetaDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.files.FileMetaDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.files.FileMetaDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.files.FileMetaDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.files.FileMetaDataResponse)
      com.example.files.FileMetaDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.files.FileMetadata.internal_static_com_example_files_FileMetaDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.files.FileMetadata.internal_static_com_example_files_FileMetaDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.files.FileMetaDataResponse.class, com.example.files.FileMetaDataResponse.Builder.class);
    }

    // Construct using com.example.files.FileMetaDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      filelength_ = 0D;

      if (dateModifiedBuilder_ == null) {
        dateModified_ = null;
      } else {
        dateModified_ = null;
        dateModifiedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.files.FileMetadata.internal_static_com_example_files_FileMetaDataResponse_descriptor;
    }

    @java.lang.Override
    public com.example.files.FileMetaDataResponse getDefaultInstanceForType() {
      return com.example.files.FileMetaDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.files.FileMetaDataResponse build() {
      com.example.files.FileMetaDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.files.FileMetaDataResponse buildPartial() {
      com.example.files.FileMetaDataResponse result = new com.example.files.FileMetaDataResponse(this);
      result.name_ = name_;
      result.filelength_ = filelength_;
      if (dateModifiedBuilder_ == null) {
        result.dateModified_ = dateModified_;
      } else {
        result.dateModified_ = dateModifiedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.files.FileMetaDataResponse) {
        return mergeFrom((com.example.files.FileMetaDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.files.FileMetaDataResponse other) {
      if (other == com.example.files.FileMetaDataResponse.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getFilelength() != 0D) {
        setFilelength(other.getFilelength());
      }
      if (other.hasDateModified()) {
        mergeDateModified(other.getDateModified());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.files.FileMetaDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.files.FileMetaDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private double filelength_ ;
    /**
     * <code>double filelength = 2;</code>
     * @return The filelength.
     */
    @java.lang.Override
    public double getFilelength() {
      return filelength_;
    }
    /**
     * <code>double filelength = 2;</code>
     * @param value The filelength to set.
     * @return This builder for chaining.
     */
    public Builder setFilelength(double value) {
      
      filelength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double filelength = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilelength() {
      
      filelength_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateModified_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateModifiedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     * @return Whether the dateModified field is set.
     */
    public boolean hasDateModified() {
      return dateModifiedBuilder_ != null || dateModified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     * @return The dateModified.
     */
    public com.google.protobuf.Timestamp getDateModified() {
      if (dateModifiedBuilder_ == null) {
        return dateModified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateModified_;
      } else {
        return dateModifiedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public Builder setDateModified(com.google.protobuf.Timestamp value) {
      if (dateModifiedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateModified_ = value;
        onChanged();
      } else {
        dateModifiedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public Builder setDateModified(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateModifiedBuilder_ == null) {
        dateModified_ = builderForValue.build();
        onChanged();
      } else {
        dateModifiedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public Builder mergeDateModified(com.google.protobuf.Timestamp value) {
      if (dateModifiedBuilder_ == null) {
        if (dateModified_ != null) {
          dateModified_ =
            com.google.protobuf.Timestamp.newBuilder(dateModified_).mergeFrom(value).buildPartial();
        } else {
          dateModified_ = value;
        }
        onChanged();
      } else {
        dateModifiedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public Builder clearDateModified() {
      if (dateModifiedBuilder_ == null) {
        dateModified_ = null;
        onChanged();
      } else {
        dateModified_ = null;
        dateModifiedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateModifiedBuilder() {
      
      onChanged();
      return getDateModifiedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateModifiedOrBuilder() {
      if (dateModifiedBuilder_ != null) {
        return dateModifiedBuilder_.getMessageOrBuilder();
      } else {
        return dateModified_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateModified_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateModified = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateModifiedFieldBuilder() {
      if (dateModifiedBuilder_ == null) {
        dateModifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateModified(),
                getParentForChildren(),
                isClean());
        dateModified_ = null;
      }
      return dateModifiedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.files.FileMetaDataResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.files.FileMetaDataResponse)
  private static final com.example.files.FileMetaDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.files.FileMetaDataResponse();
  }

  public static com.example.files.FileMetaDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileMetaDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<FileMetaDataResponse>() {
    @java.lang.Override
    public FileMetaDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileMetaDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileMetaDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileMetaDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.files.FileMetaDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

