// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

/**
 * Protobuf type {@code com.example.files.RenameFileResponse}
 */
public final class RenameFileResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.files.RenameFileResponse)
    RenameFileResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RenameFileResponse.newBuilder() to construct.
  private RenameFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenameFileResponse() {
    fromFileName_ = "";
    directory_ = "";
    toFileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RenameFileResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RenameFileResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fromFileName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            directory_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            toFileName_ = s;
            break;
          }
          case 32: {

            renameResult_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.files.FileMetadata.internal_static_com_example_files_RenameFileResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.files.FileMetadata.internal_static_com_example_files_RenameFileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.files.RenameFileResponse.class, com.example.files.RenameFileResponse.Builder.class);
  }

  public static final int FROM_FILE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object fromFileName_;
  /**
   * <code>string from_file_name = 1;</code>
   * @return The fromFileName.
   */
  @java.lang.Override
  public java.lang.String getFromFileName() {
    java.lang.Object ref = fromFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string from_file_name = 1;</code>
   * @return The bytes for fromFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromFileNameBytes() {
    java.lang.Object ref = fromFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTORY_FIELD_NUMBER = 2;
  private volatile java.lang.Object directory_;
  /**
   * <code>string directory = 2;</code>
   * @return The directory.
   */
  @java.lang.Override
  public java.lang.String getDirectory() {
    java.lang.Object ref = directory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      directory_ = s;
      return s;
    }
  }
  /**
   * <code>string directory = 2;</code>
   * @return The bytes for directory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDirectoryBytes() {
    java.lang.Object ref = directory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      directory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FILE_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object toFileName_;
  /**
   * <code>string to_file_name = 3;</code>
   * @return The toFileName.
   */
  @java.lang.Override
  public java.lang.String getToFileName() {
    java.lang.Object ref = toFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string to_file_name = 3;</code>
   * @return The bytes for toFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToFileNameBytes() {
    java.lang.Object ref = toFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RENAME_RESULT_FIELD_NUMBER = 4;
  private boolean renameResult_;
  /**
   * <code>bool rename_result = 4;</code>
   * @return The renameResult.
   */
  @java.lang.Override
  public boolean getRenameResult() {
    return renameResult_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFromFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromFileName_);
    }
    if (!getDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, directory_);
    }
    if (!getToFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toFileName_);
    }
    if (renameResult_ != false) {
      output.writeBool(4, renameResult_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFromFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromFileName_);
    }
    if (!getDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, directory_);
    }
    if (!getToFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toFileName_);
    }
    if (renameResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, renameResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.files.RenameFileResponse)) {
      return super.equals(obj);
    }
    com.example.files.RenameFileResponse other = (com.example.files.RenameFileResponse) obj;

    if (!getFromFileName()
        .equals(other.getFromFileName())) return false;
    if (!getDirectory()
        .equals(other.getDirectory())) return false;
    if (!getToFileName()
        .equals(other.getToFileName())) return false;
    if (getRenameResult()
        != other.getRenameResult()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFromFileName().hashCode();
    hash = (37 * hash) + DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getDirectory().hashCode();
    hash = (37 * hash) + TO_FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getToFileName().hashCode();
    hash = (37 * hash) + RENAME_RESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRenameResult());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.files.RenameFileResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.RenameFileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.files.RenameFileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.files.RenameFileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.files.RenameFileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.files.RenameFileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.files.RenameFileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.files.RenameFileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.files.RenameFileResponse)
      com.example.files.RenameFileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.files.FileMetadata.internal_static_com_example_files_RenameFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.files.FileMetadata.internal_static_com_example_files_RenameFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.files.RenameFileResponse.class, com.example.files.RenameFileResponse.Builder.class);
    }

    // Construct using com.example.files.RenameFileResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fromFileName_ = "";

      directory_ = "";

      toFileName_ = "";

      renameResult_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.files.FileMetadata.internal_static_com_example_files_RenameFileResponse_descriptor;
    }

    @java.lang.Override
    public com.example.files.RenameFileResponse getDefaultInstanceForType() {
      return com.example.files.RenameFileResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.files.RenameFileResponse build() {
      com.example.files.RenameFileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.files.RenameFileResponse buildPartial() {
      com.example.files.RenameFileResponse result = new com.example.files.RenameFileResponse(this);
      result.fromFileName_ = fromFileName_;
      result.directory_ = directory_;
      result.toFileName_ = toFileName_;
      result.renameResult_ = renameResult_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.files.RenameFileResponse) {
        return mergeFrom((com.example.files.RenameFileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.files.RenameFileResponse other) {
      if (other == com.example.files.RenameFileResponse.getDefaultInstance()) return this;
      if (!other.getFromFileName().isEmpty()) {
        fromFileName_ = other.fromFileName_;
        onChanged();
      }
      if (!other.getDirectory().isEmpty()) {
        directory_ = other.directory_;
        onChanged();
      }
      if (!other.getToFileName().isEmpty()) {
        toFileName_ = other.toFileName_;
        onChanged();
      }
      if (other.getRenameResult() != false) {
        setRenameResult(other.getRenameResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.files.RenameFileResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.files.RenameFileResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fromFileName_ = "";
    /**
     * <code>string from_file_name = 1;</code>
     * @return The fromFileName.
     */
    public java.lang.String getFromFileName() {
      java.lang.Object ref = fromFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from_file_name = 1;</code>
     * @return The bytes for fromFileName.
     */
    public com.google.protobuf.ByteString
        getFromFileNameBytes() {
      java.lang.Object ref = fromFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from_file_name = 1;</code>
     * @param value The fromFileName to set.
     * @return This builder for chaining.
     */
    public Builder setFromFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from_file_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromFileName() {
      
      fromFileName_ = getDefaultInstance().getFromFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string from_file_name = 1;</code>
     * @param value The bytes for fromFileName to set.
     * @return This builder for chaining.
     */
    public Builder setFromFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromFileName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object directory_ = "";
    /**
     * <code>string directory = 2;</code>
     * @return The directory.
     */
    public java.lang.String getDirectory() {
      java.lang.Object ref = directory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        directory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string directory = 2;</code>
     * @return The bytes for directory.
     */
    public com.google.protobuf.ByteString
        getDirectoryBytes() {
      java.lang.Object ref = directory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        directory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string directory = 2;</code>
     * @param value The directory to set.
     * @return This builder for chaining.
     */
    public Builder setDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      directory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string directory = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirectory() {
      
      directory_ = getDefaultInstance().getDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>string directory = 2;</code>
     * @param value The bytes for directory to set.
     * @return This builder for chaining.
     */
    public Builder setDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      directory_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toFileName_ = "";
    /**
     * <code>string to_file_name = 3;</code>
     * @return The toFileName.
     */
    public java.lang.String getToFileName() {
      java.lang.Object ref = toFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string to_file_name = 3;</code>
     * @return The bytes for toFileName.
     */
    public com.google.protobuf.ByteString
        getToFileNameBytes() {
      java.lang.Object ref = toFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to_file_name = 3;</code>
     * @param value The toFileName to set.
     * @return This builder for chaining.
     */
    public Builder setToFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to_file_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToFileName() {
      
      toFileName_ = getDefaultInstance().getToFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string to_file_name = 3;</code>
     * @param value The bytes for toFileName to set.
     * @return This builder for chaining.
     */
    public Builder setToFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toFileName_ = value;
      onChanged();
      return this;
    }

    private boolean renameResult_ ;
    /**
     * <code>bool rename_result = 4;</code>
     * @return The renameResult.
     */
    @java.lang.Override
    public boolean getRenameResult() {
      return renameResult_;
    }
    /**
     * <code>bool rename_result = 4;</code>
     * @param value The renameResult to set.
     * @return This builder for chaining.
     */
    public Builder setRenameResult(boolean value) {
      
      renameResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool rename_result = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRenameResult() {
      
      renameResult_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.files.RenameFileResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.files.RenameFileResponse)
  private static final com.example.files.RenameFileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.files.RenameFileResponse();
  }

  public static com.example.files.RenameFileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenameFileResponse>
      PARSER = new com.google.protobuf.AbstractParser<RenameFileResponse>() {
    @java.lang.Override
    public RenameFileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RenameFileResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RenameFileResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenameFileResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.files.RenameFileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

