// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface RenameFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.RenameFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_file_name = 1;</code>
   * @return The fromFileName.
   */
  java.lang.String getFromFileName();
  /**
   * <code>string from_file_name = 1;</code>
   * @return The bytes for fromFileName.
   */
  com.google.protobuf.ByteString
      getFromFileNameBytes();

  /**
   * <code>string directory = 2;</code>
   * @return The directory.
   */
  java.lang.String getDirectory();
  /**
   * <code>string directory = 2;</code>
   * @return The bytes for directory.
   */
  com.google.protobuf.ByteString
      getDirectoryBytes();

  /**
   * <code>string to_file_name = 3;</code>
   * @return The toFileName.
   */
  java.lang.String getToFileName();
  /**
   * <code>string to_file_name = 3;</code>
   * @return The bytes for toFileName.
   */
  com.google.protobuf.ByteString
      getToFileNameBytes();
}
