// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface SortInputResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.SortInputResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 output = 1;</code>
   * @return A list containing the output.
   */
  java.util.List<java.lang.Integer> getOutputList();
  /**
   * <code>repeated int32 output = 1;</code>
   * @return The count of output.
   */
  int getOutputCount();
  /**
   * <code>repeated int32 output = 1;</code>
   * @param index The index of the element to return.
   * @return The output at the given index.
   */
  int getOutput(int index);
}
