// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file-metadata.proto

package com.example.files;

public interface SortInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.files.SortInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 input = 1;</code>
   * @return A list containing the input.
   */
  java.util.List<java.lang.Integer> getInputList();
  /**
   * <code>repeated int32 input = 1;</code>
   * @return The count of input.
   */
  int getInputCount();
  /**
   * <code>repeated int32 input = 1;</code>
   * @param index The index of the element to return.
   * @return The input at the given index.
   */
  int getInput(int index);
}
